#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Data::Dumper; 
use HTTP::Tiny;
use JSON::PP;
use Term::ANSIColor;
use App::Trrr::HotKey qw< readkey >;
use App::Trrr::Open qw< open_app >;

my $help = <<'EOT';

USAGE: 
    	trrr keyword1 keyword2 -N 
			
			- search
	    trrr big lebowski
	    
	    - limitt search where seeders > 10
	    trrr big lebowski -10


EOT

say $help unless @ARGV;

my $seeds = 1; 
$seeds = $ARGV[$#ARGV] if $ARGV[$#ARGV] =~ /^-/; 
$seeds =~ s/-//;
my $torrent_file = "$ENV{HOME}/.trrr.torrent";
my $url = 'http://extratorrent.cc/json/?cid=4&search=' . join '+', @ARGV;

my $response = HTTP::Tiny->new->get($url);

my $results = decode_json $response->{content};
my @filter = grep { $_->{seeds} > $seeds } @{$results->{list}};
@filter = sort { $b->{seeds} <=> $a->{seeds} } @filter;
@filter = splice(@filter,0,15);

my $term_width  = `tput cols`; 

my $key = 'A';
my $key_color;
my $i = 1;

sub strip_title {
    my $item = shift;
    my $title;

    my $line = '-' . "-" . $item->{seeds} . "-" . $item->{title} . "-" . $item->{size} . 'M' . '-';

    if( $term_width < length($line)){
        my $strip = length($line) - $term_width;
        my $stripped_title = $term_width - $strip;
        $title = substr( $item->{title},0,$stripped_title );
        #say "title: $title";
        #say "strip is" .  $strip;
        #say "stripped_title" . $stripped_title;
    } else { $title = $item->{title} }
    return $title;
}

for(@filter){
    if( $i % 2 ){ $key_color = 'black on_white' } else { $key_color = 'white on_black' }
    $_->{key} = $key;

    #say 'real title:' . $_->{title};
    say colored([$key_color],$key) . "\ " . colored(['blue'],$_->{seeds}) . "\ " .  colored(['yellow'],strip_title($_)) . "\ " . $_->{size} . 'M';
    $key++; $i++;
}
#die;

my $pick = readkey();
my @picked = grep { $_->{key} eq uc $pick } @filter;
#my @picked = grep { $_->{key} eq $pick } @filter;

for(@picked){ 
    my $torrent = HTTP::Tiny->new->get("$_->{torrentLink}");
    open(my $fh,'>',$torrent_file)||die "cant open $torrent_file: $!";
    print $fh $torrent->{content};
    close $fh;
    open_app($torrent_file);
}


__DATA__
iOS iTransmission path
'/private/var/mobile/Library/Application Support/Containers/com.ioshomebrew.itransmission/Documents/Inbox/'

OSX /Applications/WebTorrent.app/Contents//MacOS/WebTorrent

$VAR1 = { 'link' => 'http://extratorrent.cc', 'description' => 'Extratorrent Search: big lebowski', 'title' => 'Extratorrent Search: big lebowski', 'list' => [ { 'files' => 17, 'torrentLink' => 'http://extratorrent.cc/download/2277121/', 'leechs' => -1, 'link' => 'http://extratorrent.cc/torrent/2277121/', 'hash' => 'b7cbd4a6be50403f17df469f3759d17a82ee6c28', 'category' => 'Movies', 'subcategory' => 'Comedy', 'seeds' => -1, ], 'total_results' => 73 };

